services:
  real_estate_listings_app:
    image: ${DOCKERHUB_USERNAME}/real-estate-listings:latest
    container_name: real_estate_listings_app
    restart: always
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    depends_on:
      - real_estate_listings_postgres
      - real_estate_listings_redis

  real_estate_listings_postgres:
    image: postgres:alpine
    container_name: real_estate_listings_postgres
    restart: always
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  real_estate_listings_redis:
    image: redis:alpine
    container_name: real_estate_listings_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis_data:/data

networks:
  default:
    name: real_estate_listings

volumes:
  postgres_data:
  redis_data:
