services:
  real_estate_listings_postgres_test:
    image: postgres:alpine
    container_name: real_estate_listings_postgres_test
    restart: no
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
  
  real_estate_listings_redis_test:
    image: redis:alpine
    container_name: real_estate_listings_redis_test
    restart: no
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6381:6379'
    volumes:
      - redis_test_data:/data

networks:
  default:
    name: real_estate_listings_test

volumes:
  postgres_test_data:
  redis_test_data:
